### ISSUE TITLE
Change "get" to "getting" 

### ISSUE THREAD

**Issue by SixFiveSoftware** [editorscut/ec013async#1]
<img width="912" alt="Screenshot 2023-01-01 at 3 16 45 PM" src="https://user-images.githubusercontent.com/2272819/210183572-2d70d8a4-1f2c-4f2b-9012-ecc43bf1b3e6.png">

The second sentence has "get" vs "getting":

"In this chapter we look at getting a sequence of responses as they become available."

Note: this is in the beta 3 text.

**Comment by dimsumthinking** [comment]
Thank you - fixed
