### ISSUE TITLE
P155 randomNumber() code block has Build error

### ISSUE THREAD

**Issue by nigelhamilton** [editorscut/ec013async#14]
![BuildError](https://user-images.githubusercontent.com/6199898/213471477-0a60b45a-d7a8-4c89-ac8c-a25f2db67a57.png)

**Comment by nigelhamilton** [comment]
Also, I suspect that the code block should be using intURL, or the book should say to test with both??

**Comment by dimsumthinking** [comment]
Thanks - changed this to an if let and fixed the URL. Thank you
