### ISSUE TITLE
Ch 3 Section 2 Wrong Async refactor

### ISSUE THREAD

**Issue by nigelhamilton** [editorscut/ec013async#15]
In the False Step section, I had to refactor using Add Async Wrapper (rather than Add Async Alternative) to get the code shown.

**Comment by dimsumthinking** [comment]
I changed this to use Async Alternative - which was my intent. Thank you for calling this out. Fixed

**Comment by dimsumthinking** [comment]
Nigel,

Hi,

I’m wrapping up the Async book and want to include your name in the credits. How would you like your name to appear?

Thanks,

Daniel

**Comment by nigelhamilton** [comment]
Hi Daniel,
That is so nice of you 😀. “Nigel Hamilton” would be fine.
By the way, are you planning to go to Aberystwyth this year?

Best wishes,
Nigel

**Comment by dimsumthinking** [comment]
Thank you - I will always go if I'm invited. Chris is on the list of people I never say "no" to
