### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by dantonchin** [editorscut/ec013async#16]
“version 0.4 for Swift 5.7, Xcode 14.2, macOS Ventura 13.0, and iOS 16.1 released January 2023”
Chapter 1, Section 7, subsection XCTAssertThrows Error

“do {
      let result = try await vendor.imageName(for: 53)”

test does not pass: testImageNameCreatesEntry(): XCTAssertEqual failed: ("2.circle") is not equal to ("3.circle")

The **for** value should be **3**.

Excerpt From
The Curious Case of the Async Cafe
Daniel H Steinberg
This material may be protected by copyright.

**Comment by dimsumthinking** [comment]
Thank you - this is fixed. I hope you are well
