### ISSUE TITLE
Chapter 5, section 2 `guard let`

### ISSUE THREAD

**Issue by walcamla** [editorscut/ec013async#18]
_Instead, let's introduce a guard let at the top to make a local, unwrapped **copy** of monitor that is captured by the Tasks._

I have always find this a bit confusing, given that `monitor` is a reference type and in fact it is the same underlying object the one being modified. I know this is correct, but a little reminder of reference behavior here might be helpful?

**Comment by dimsumthinking** [comment]
The idea is that monitor is an optional reference to an instance of ProgressMonitor - in other words monitor’s type is ProgressMonitor? . This means every time we use it we’d have to unwrap it somehow and this makes the code more complicated - so instead I made a new local variable named monitor. Perhaps you’d prefer we called it unwrappedMonitor.

Essentially we’re saying if monitor is nil just return, if it is not nil, unwrap it and store the unwrapped value (which as you point out is a reference) in unwrappedMonitor. The standard practice in Swift is to give the unwrapped value the same name.

Does that help?

Daniel

**Comment by walcamla** [comment]
Yes, it helps, and I got it, but probably just doing a little call out that this is a reference type (and thus we are actually just copying the reference to it) might be good for less experienced readers. Now I have gone a bit further with the reading and you do a pretty good explanation of all of this in the section `The job of an actor`, so I probably tried to do this suggestion a bit too early on my reading. 

Thanks Daniel!

**Comment by dimsumthinking** [comment]
Thank you for taking the time
