### ISSUE TITLE
Chapter 5 section 5

### ISSUE THREAD

**Issue by walcamla** [editorscut/ec013async#19]
An isolated method should be isolated

Code sample just below **_If we make it isolated, look how much simpler it is_.**, has incorrect strikethrough text. Also, the task should have strikethrough to get 

```swift 
    func header() {
        print("\n================== \n", searchTerm, 
              "has ", total, "results")
        separator()
    }
```

**Comment by dimsumthinking** [comment]
Thank you.

I apologize for the error and - thanks to you - this is corrected for the next release.
