### ISSUE TITLE
Ch1 p28 verb tense 

### ISSUE THREAD

**Issue by SixFiveSoftware** [editorscut/ec013async#2]
On page 28 (in pdf format) of chapter 1, the tense seems like the current project already has a way of consuming a published property in MainView, but it seems confusing as I look in the project and nothing is there yet. Perhaps future tense, like "we will regsiter" vs "we register"? After reading that sentence I went to look at the project, and didn't see the observer yet. 

<img width="839" alt="image" src="https://user-images.githubusercontent.com/2272819/210184206-3558694d-98ab-40f0-a729-0ea7c106c9f7.png">

**Comment by dimsumthinking** [comment]
Thank you - fixed
