### ISSUE TITLE
Ch1 p92 test question

### ISSUE THREAD

**Issue by SixFiveSoftware** [editorscut/ec013async#5]
I think you meant to use `vendor.entry(for: 3)` in the test, vs `vendor.entry(for: 203)`? at the end of the page it says the test should pass, but not with 203. 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2272819/210616303-d86e036d-7b8b-4b4a-83ca-5f35b7363596.png">

**Comment by SixFiveSoftware** [comment]
also...there's more places the 203 is listed. then, in a subsequent test when testing `imageName(for: 53)` it is assumed to pass. mine does not, and i feel it's because of the `let number = int % 51` line in AsyncEntryVendor. should it be `% 50`? 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/2272819/210617329-3efd060c-2629-465b-bd92-668a706f5b5b.png">

**Comment by dimsumthinking** [comment]
Thanks - I initially did this on purpose because the numbers were % 50 but they aren't anymore and you're right this makes it more confusing. Thank you - fixed.
